### PR TITLE
Embedded notes

### PR DESCRIPTION
**Pull request by r888888888**
This is a new feature to embed text in the note boxes to remove the need to hover to read the text. It is conditionally activated on a per-post basis with a new boolean flag.

### CODE REVIEW

**Comment by ToksT** [comment]
The opacity of notes was raised to 90%, which is fine for reading, but I think it should be brought back down when translation mode is turned on or it's difficult to read the original text.

**Comment by ToksT** [comment]
> It is conditionally activated on a per-post basis with a new boolean flag.

It's possible to detect which notes have text that is too big to fit in the note box, so we could automatically disable it for those specific notes rather than asking the user manually. Although, I guess it might look weird to have some notes with embedded text and some not on the same post.

**Comment by ToksT** [comment]
We could center the text (horizontally+vertically) within the note box with css like this:

```css
div.note-box.with-embedded-text div.note-box-inner-border {
  text-align: center;
  display: table-cell;
  vertical-align: middle;
}
```

Seems to work fine in most situations, but when the text is too big for the note as mentioned earlier it will cause the note itself to expand as well. So we may want to do something about these small notes before implementing text centering.

**Comment by r888888888** [comment]
The text could be truncated in the box.

But IMO if a post is translated with embedded notes in mind, the translator will resize the note accordingly to accommodate the text. All the previous tricks with CSS and font styling should still work.

**Comment by r888888888** [comment]
I've incorporated @ToksT ideas and have deployed to testbooru.

**Comment by r888888888** [comment]
The display: table-cell breaks overflow: hidden so when the note is really small the display breaks, although the resizer still behaves correctly. The overflow works correctly if the display is set to block but then you lose vertical centering.

**Pull request merged**
